package coresight

import "errors"

var (
	errFail                  = errors.New("general failure")
	errMem                   = errors.New("internal memory allocation error")
	errNotInit               = errors.New("component not initialised")
	errInvalidID             = errors.New("invalid CoreSight Trace Source ID")
	errBadHandle             = errors.New("invalid handle passed to component")
	errInvalidParamVal       = errors.New("invalid value parameter passed to component")
	errInvalidParamType      = errors.New("type mismatch on abstract interface")
	errFileError             = errors.New("file access error")
	errNoProtocol            = errors.New("trace protocol unsupported")
	errAttachTooMany         = errors.New("cannot attach - attach device limit reached")
	errAttachInvalidParam    = errors.New("cannot attach - invalid parameter")
	errAttachCompNotFound    = errors.New("cannot detach - component not found")
	errRdrFileNotFound       = errors.New("source reader - file not found")
	errRdrInvalidInit        = errors.New("source reader - invalid initialisation parameter")
	errRdrNoDecoder          = errors.New("source reader - no trace decoder set")
	ErrDataDecodeFatal       = errors.New("a decoder in the data path has returned a fatal error")
	errDfrmtrNotconttrace    = errors.New("trace input to deformatter non-continuous")
	errDfrmtrBadFhsync       = errors.New("bad frame or half frame sync in trace deformatter")
	errDfrmtrUnaligned       = errors.New("insufficient bytes for aligned frame")
	errDfrmtrBadFsyncReset   = errors.New("incorrect FSYNC frame reset pattern")
	errDfrmtrBadHSync        = errors.New("bad HSYNC in frame")
	errDfrmtrBadFsyncStart   = errors.New("bad FSYNC start in frame or invalid ID (0x7F)")
	errDfrmtrOddByte         = errors.New("odd trailing byte in frame stream")
	errDfrmtrNotConfigured   = errors.New("deformatter not configured")
	errBadPacketSeq          = errors.New("bad packet sequence")
	errInvalidPcktHdr        = errors.New("invalid packet header")
	errPktInterpFail         = errors.New("interpreter failed - cannot recover - bad data or sequence")
	errUnsupportedISA        = errors.New("ISA not supported in decoder")
	errHWCfgUnsupp           = errors.New("programmed trace configuration not supported by decoder")
	errUnsuppDecodePkt       = errors.New("packet not supported in decoder")
	errBadDecodePkt          = errors.New("reserved or unknown packet in decoder")
	errCommitPktOverrun      = errors.New("overrun in commit packet stack - tried to commit more than available")
	errMemNacc               = errors.New("unable to access required memory address")
	errRetStackOverflow      = errors.New("internal return stack overflow checks failed - popped more than we pushed")
	errDcdtNoFormatter       = errors.New("no formatter in use - operation not valid")
	ErrMemAccOverlap         = errors.New("attempted to set an overlapping range in memory access map")
	errMemAccFileNotFound    = errors.New("memory access file could not be opened")
	errMemAccFileDiffRange   = errors.New("attempt to re-use the same memory access file for a different address range")
	errMemAccRangeInvalid    = errors.New("address range in accessor set to invalid values")
	errMemAccBadLen          = errors.New("memory accessor returned a bad read length value (larger than requested)")
	errTestSnapshotParse     = errors.New("test snapshot file parse error")
	errTestSnapshotParseInfo = errors.New("test snapshot file parse information")
	errTestSnapshotRead      = errors.New("test snapshot reader error")
	errTestSSToDecoder       = errors.New("test snapshot to decode tree conversion error")
	errDcdregNameRepeat      = errors.New("attempted to register a decoder with the same name as another one")
	errDcdregNameUnknown     = errors.New("attempted to find a decoder with a name that is not known in the library")
	errDcdregTypeUnknown     = errors.New("attempted to find a decoder with a type that is not known in the library")
	errDcdregToomany         = errors.New("attempted to register too many custom decoders")
	errDcdInterfaceUnused    = errors.New("attempt to connect or use and interface not supported by this decoder")
	errInvalidOpcode         = errors.New("illegal Opcode found while decoding program memory")
	errIRangeLimitOverrun    = errors.New("an optional limit on consecutive instructions in range during decode has been exceeded")
	errBadDecodeImage        = errors.New("mismatch between trace packets and decode image")
)
