package protocol

import "errors"

var (
	ErrFail                  = errors.New("general failure")
	ErrMem                   = errors.New("internal memory allocation error")
	ErrNotInit               = errors.New("component not initialised")
	ErrInvalidID             = errors.New("invalid CoreSight Trace Source ID")
	ErrBadHandle             = errors.New("invalid handle passed to component")
	ErrInvalidParamVal       = errors.New("invalid value parameter passed to component")
	ErrInvalidParamType      = errors.New("type mismatch on abstract interface")
	ErrFileError             = errors.New("file access error")
	ErrNoProtocol            = errors.New("trace protocol unsupported")
	ErrAttachTooMany         = errors.New("cannot attach - attach device limit reached")
	ErrAttachInvalidParam    = errors.New("cannot attach - invalid parameter")
	ErrAttachCompNotFound    = errors.New("cannot detach - component not found")
	ErrRdrFileNotFound       = errors.New("source reader - file not found")
	ErrRdrInvalidInit        = errors.New("source reader - invalid initialisation parameter")
	ErrRdrNoDecoder          = errors.New("source reader - no trace decoder set")
	ErrDataDecodeFatal       = errors.New("a decoder in the data path has returned a fatal error")
	ErrDfrmtrNotconttrace    = errors.New("trace input to deformatter non-continuous")
	ErrDfrmtrBadFhsync       = errors.New("bad frame or half frame sync in trace deformatter")
	ErrDfrmtrUnaligned       = errors.New("insufficient bytes for aligned frame")
	ErrDfrmtrBadFsyncReset   = errors.New("incorrect FSYNC frame reset pattern")
	ErrDfrmtrBadHSync        = errors.New("bad HSYNC in frame")
	ErrDfrmtrBadFsyncStart   = errors.New("bad FSYNC start in frame or invalid ID (0x7F)")
	ErrDfrmtrOddByte         = errors.New("odd trailing byte in frame stream")
	ErrDfrmtrNotConfigured   = errors.New("deformatter not configured")
	ErrBadPacketSeq          = errors.New("bad packet sequence")
	ErrInvalidPcktHdr        = errors.New("invalid packet header")
	ErrPktInterpFail         = errors.New("interpreter failed - cannot recover - bad data or sequence")
	ErrUnsupportedISA        = errors.New("ISA not supported in decoder")
	ErrHWCfgUnsupp           = errors.New("programmed trace configuration not supported by decoder")
	ErrUnsuppDecodePkt       = errors.New("packet not supported in decoder")
	ErrBadDecodePkt          = errors.New("reserved or unknown packet in decoder")
	ErrCommitPktOverrun      = errors.New("overrun in commit packet stack - tried to commit more than available")
	ErrMemNacc               = errors.New("unable to access required memory address")
	ErrRetStackOverflow      = errors.New("internal return stack overflow checks failed - popped more than we pushed")
	ErrDcdtNoFormatter       = errors.New("no formatter in use - operation not valid")
	ErrMemAccOverlap         = errors.New("attempted to set an overlapping range in memory access map")
	ErrMemAccFileNotFound    = errors.New("memory access file could not be opened")
	ErrMemAccFileDiffRange   = errors.New("attempt to re-use the same memory access file for a different address range")
	ErrMemAccRangeInvalid    = errors.New("address range in accessor set to invalid values")
	ErrMemAccBadLen          = errors.New("memory accessor returned a bad read length value (larger than requested)")
	ErrTestSnapshotParse     = errors.New("test snapshot file parse error")
	ErrTestSnapshotParseInfo = errors.New("test snapshot file parse information")
	ErrTestSnapshotRead      = errors.New("test snapshot reader error")
	ErrTestSSToDecoder       = errors.New("test snapshot to decode tree conversion error")
	ErrDcdregNameRepeat      = errors.New("attempted to register a decoder with the same name as another one")
	ErrDcdregNameUnknown     = errors.New("attempted to find a decoder with a name that is not known in the library")
	ErrDcdregTypeUnknown     = errors.New("attempted to find a decoder with a type that is not known in the library")
	ErrDcdregToomany         = errors.New("attempted to register too many custom decoders")
	ErrDcdInterfaceUnused    = errors.New("attempt to connect or use and interface not supported by this decoder")
	ErrInvalidOpcode         = errors.New("illegal Opcode found while decoding program memory")
	ErrIRangeLimitOverrun    = errors.New("an optional limit on consecutive instructions in range during decode has been exceeded")
	ErrBadDecodeImage        = errors.New("mismatch between trace packets and decode image")
)
